import { calculateTradeProfit, resolveTradeStatus } from "./calculations";
import type { BankrollOperation, BankrollRule, BetMarket, BettingStrategy, EntryMethod, RiskPlan } from "./types";

export const initialBankroll = 5000;

export const betfairMarkets: BetMarket[] = [
  "Match Odds",
  "Correct Score",
  "Over/Under Goals",
  "Both Teams To Score",
  "Asian Handicap",
  "Corners",
  "Tennis Match Odds",
  "Basketball Totals",
];

export const entryMethods: EntryMethod[] = [
  "Value pré-live",
  "Scalping de ticks",
  "Swing trade",
  "Lay ao favorito",
  "Back ao underdog",
  "Leitura de pressão",
  "Hedge de posição",
];

export const strategies: BettingStrategy[] = [
  {
    id: "match-odds-swing",
    name: "Swing Match Odds",
    market: "Match Odds",
    riskLevel: "moderado",
    targetRoi: 7,
    maxStakePercentage: 2,
  },
  {
    id: "favorite-lay",
    name: "Lay Favorito Pressionado",
    market: "Match Odds",
    riskLevel: "agressivo",
    targetRoi: 10,
    maxStakePercentage: 1.5,
  },
  {
    id: "goals-pressure",
    name: "Over Goals por Pressão",
    market: "Over/Under Goals",
    riskLevel: "moderado",
    targetRoi: 8,
    maxStakePercentage: 1.25,
  },
  {
    id: "corners-scalp",
    name: "Scalping em Escanteios",
    market: "Corners",
    riskLevel: "conservador",
    targetRoi: 4,
    maxStakePercentage: 1,
  },
];

type OperationSeed = Omit<BankrollOperation, "profit" | "status" | "goalImpact"> & {
  status?: BankrollOperation["status"];
  goalImpact?: BankrollOperation["goalImpact"];
};

const buildOperation = (operation: OperationSeed): BankrollOperation => {
  const profit = operation.status === "open" || operation.status === "void"
    ? 0
    : calculateTradeProfit(operation.side, operation.stake, operation.entryOdds, operation.exitOdds);

  return {
    goalImpact: "sem gol",
    ...operation,
    profit,
    status: operation.status ?? resolveTradeStatus(profit),
  };
};

export const operations: BankrollOperation[] = [
  buildOperation({
    id: "op-001",
    date: "2026-04-21",
    strategyId: "match-odds-swing",
    method: "Swing trade",
    market: "Match Odds",
    competition: "Premier League",
    homeTeam: "Arsenal",
    awayTeam: "Chelsea",
    selection: "Arsenal",
    side: "Back",
    entryOdds: 2.24,
    exitOdds: 1.92,
    entryMinute: 18,
    exitMinute: 41,
    goalImpact: "sem gol",
    stake: 120,
  }),
  buildOperation({
    id: "op-002",
    date: "2026-04-22",
    strategyId: "favorite-lay",
    method: "Lay ao favorito",
    market: "Match Odds",
    competition: "Serie A",
    homeTeam: "Roma",
    awayTeam: "Lazio",
    selection: "Roma",
    side: "Lay",
    entryOdds: 1.78,
    exitOdds: 2.08,
    entryMinute: 22,
    exitMinute: 53,
    goalImpact: "gol contra",
    stake: 90,
  }),
  buildOperation({
    id: "op-003",
    date: "2026-04-23",
    strategyId: "goals-pressure",
    method: "Leitura de pressão",
    market: "Over/Under Goals",
    competition: "LaLiga",
    homeTeam: "Real Sociedad",
    awayTeam: "Villarreal",
    selection: "Over 2.5 Goals",
    side: "Back",
    entryOdds: 2.1,
    exitOdds: 1.83,
    entryMinute: 61,
    exitMinute: 72,
    goalImpact: "gol a favor",
    stake: 80,
  }),
  buildOperation({
    id: "op-004",
    date: "2026-04-24",
    strategyId: "corners-scalp",
    method: "Scalping de ticks",
    market: "Corners",
    competition: "Brasileirão Série A",
    homeTeam: "Flamengo",
    awayTeam: "Palmeiras",
    selection: "Over 9.5 Corners",
    side: "Back",
    entryOdds: 1.96,
    exitOdds: 1.88,
    entryMinute: 34,
    exitMinute: 39,
    goalImpact: "sem gol",
    stake: 70,
  }),
  buildOperation({
    id: "op-005",
    date: "2026-04-25",
    strategyId: "match-odds-swing",
    method: "Value pré-live",
    market: "Match Odds",
    competition: "Primeira Liga",
    homeTeam: "Benfica",
    awayTeam: "Porto",
    selection: "Benfica",
    side: "Back",
    entryOdds: 2.36,
    exitOdds: 2.58,
    entryMinute: 12,
    exitMinute: 29,
    goalImpact: "gol contra",
    stake: 110,
  }),
  buildOperation({
    id: "op-006",
    date: "2026-04-26",
    strategyId: "goals-pressure",
    method: "Leitura de pressão",
    market: "Both Teams To Score",
    competition: "Championship",
    homeTeam: "Leeds",
    awayTeam: "Norwich",
    selection: "Yes",
    side: "Back",
    entryOdds: 1.92,
    exitOdds: 1.74,
    entryMinute: 56,
    exitMinute: 68,
    goalImpact: "gol a favor",
    stake: 95,
  }),
  buildOperation({
    id: "op-007",
    date: "2026-04-27",
    strategyId: "favorite-lay",
    method: "Lay ao favorito",
    market: "Match Odds",
    competition: "Ligue 1",
    homeTeam: "PSG",
    awayTeam: "Marseille",
    selection: "PSG",
    side: "Lay",
    entryOdds: 1.42,
    exitOdds: 1.34,
    entryMinute: 8,
    exitMinute: 24,
    goalImpact: "sem gol",
    stake: 100,
  }),
  buildOperation({
    id: "op-008",
    date: "2026-04-28",
    strategyId: "corners-scalp",
    method: "Scalping de ticks",
    market: "Corners",
    competition: "Premier League",
    homeTeam: "Liverpool",
    awayTeam: "Manchester City",
    selection: "Over 8.5 Corners",
    side: "Back",
    entryOdds: 1.74,
    exitOdds: 1.69,
    entryMinute: 70,
    exitMinute: 76,
    goalImpact: "sem gol",
    stake: 75,
  }),
  buildOperation({
    id: "op-009",
    date: "2026-04-29",
    strategyId: "match-odds-swing",
    method: "Back ao underdog",
    market: "Match Odds",
    competition: "Copa Libertadores",
    homeTeam: "River Plate",
    awayTeam: "Atlético Nacional",
    selection: "Atlético Nacional",
    side: "Back",
    entryOdds: 5.4,
    exitOdds: 4.6,
    entryMinute: 31,
    exitMinute: 48,
    goalImpact: "gol a favor",
    stake: 55,
  }),
  buildOperation({
    id: "op-010",
    date: "2026-04-30",
    strategyId: "goals-pressure",
    method: "Hedge de posição",
    market: "Over/Under Goals",
    competition: "Bundesliga",
    homeTeam: "Bayern Munich",
    awayTeam: "Dortmund",
    selection: "Under 3.5 Goals",
    side: "Lay",
    entryOdds: 1.64,
    exitOdds: 1.72,
    entryMinute: 44,
    exitMinute: 62,
    goalImpact: "ambos",
    stake: 85,
  }),
  buildOperation({
    id: "op-011",
    date: "2026-05-01",
    strategyId: "match-odds-swing",
    method: "Swing trade",
    market: "Match Odds",
    competition: "LaLiga",
    homeTeam: "Real Madrid",
    awayTeam: "Atlético Madrid",
    selection: "Real Madrid",
    side: "Back",
    entryOdds: 1.88,
    exitOdds: 1.72,
    entryMinute: 15,
    exitMinute: 37,
    goalImpact: "sem gol",
    stake: 130,
  }),
  buildOperation({
    id: "op-012",
    date: "2026-05-02",
    strategyId: "corners-scalp",
    method: "Scalping de ticks",
    market: "Corners",
    competition: "Brasileirão Série A",
    homeTeam: "Santos",
    awayTeam: "São Paulo",
    selection: "Over 10.5 Corners",
    side: "Back",
    entryOdds: 2.04,
    exitOdds: 2.18,
    entryMinute: 63,
    exitMinute: 71,
    goalImpact: "gol contra",
    stake: 70,
  }),
  buildOperation({
    id: "op-013",
    date: "2026-05-03",
    strategyId: "favorite-lay",
    method: "Lay ao favorito",
    market: "Match Odds",
    competition: "Serie A",
    homeTeam: "Inter",
    awayTeam: "Milan",
    selection: "Inter",
    side: "Lay",
    entryOdds: 1.86,
    exitOdds: 2.22,
    entryMinute: 52,
    exitMinute: 77,
    goalImpact: "gol contra",
    stake: 95,
  }),
  buildOperation({
    id: "op-014",
    date: "2026-05-04",
    strategyId: "goals-pressure",
    method: "Leitura de pressão",
    market: "Over/Under Goals",
    competition: "Eredivisie",
    homeTeam: "Ajax",
    awayTeam: "PSV",
    selection: "Over 3.5 Goals",
    side: "Back",
    entryOdds: 2.34,
    exitOdds: 2.62,
    entryMinute: 58,
    exitMinute: 66,
    goalImpact: "gol contra",
    stake: 80,
  }),
  buildOperation({
    id: "op-015",
    date: "2026-05-05",
    strategyId: "match-odds-swing",
    method: "Hedge de posição",
    market: "Match Odds",
    competition: "Premier League",
    homeTeam: "Tottenham",
    awayTeam: "Newcastle",
    selection: "Tottenham",
    side: "Back",
    entryOdds: 2.48,
    entryMinute: 26,
    goalImpact: "sem gol",
    stake: 100,
    status: "open",
  }),
];

export const riskPlan: RiskPlan = {
  profile: "moderado",
  initialBankroll,
  currentBankroll: 0,
  maxDailyExposure: 350,
  maxStakePercentage: 2,
  stopLossPercentage: 8,
  takeProfitPercentage: 15,
};

export const bankrollRules: BankrollRule[] = [
  {
    id: "rule-001",
    title: "Responsabilidade máxima por trade",
    description: "Na Betfair, calcule exposição por responsabilidade: stake no Back e liability no Lay nunca devem superar 2% da banca.",
    severity: "critical",
  },
  {
    id: "rule-002",
    title: "Stop loss por sessão",
    description: "Encerre a sessão ao atingir 3 reds consecutivos ou 8% de perda semanal, sem tentar recuperar no live.",
    severity: "warning",
  },
  {
    id: "rule-003",
    title: "Liquidez e spread",
    description: "Evite entradas com spread alto, mercado sem volume ou campeonato fora do plano operacional.",
    severity: "info",
  },
  {
    id: "rule-004",
    title: "Saída sempre planejada",
    description: "Todo trade deve nascer com odd de entrada, odd alvo de saída, stop técnico e critério de hedge.",
    severity: "warning",
  },
];
