import type { BankrollOperation, BankrollRule, BettingStrategy, RiskPlan } from "./types";

export const initialBankroll = 5000;

export const strategies: BettingStrategy[] = [
  {
    id: "value-live",
    name: "Value Bet Live",
    market: "Futebol",
    riskLevel: "moderado",
    targetRoi: 8,
    maxStakePercentage: 2,
  },
  {
    id: "corners-pro",
    name: "Escanteios Pro",
    market: "Escanteios",
    riskLevel: "agressivo",
    targetRoi: 12,
    maxStakePercentage: 1.5,
  },
  {
    id: "tennis-hold",
    name: "Tênis Hold Serve",
    market: "Tênis",
    riskLevel: "conservador",
    targetRoi: 5,
    maxStakePercentage: 1,
  },
  {
    id: "nba-totals",
    name: "NBA Totals",
    market: "Over/Under",
    riskLevel: "moderado",
    targetRoi: 7,
    maxStakePercentage: 1.25,
  },
];

export const operations: BankrollOperation[] = [
  {
    id: "op-001",
    date: "2026-04-21",
    strategyId: "value-live",
    market: "Futebol",
    event: "Arsenal x Chelsea",
    selection: "Arsenal DNB",
    odds: 1.82,
    stake: 110,
    profit: 90.2,
    status: "green",
  },
  {
    id: "op-002",
    date: "2026-04-22",
    strategyId: "corners-pro",
    market: "Escanteios",
    event: "Roma x Lazio",
    selection: "Over 9.5 cantos",
    odds: 1.95,
    stake: 85,
    profit: -85,
    status: "red",
  },
  {
    id: "op-003",
    date: "2026-04-23",
    strategyId: "tennis-hold",
    market: "Tênis",
    event: "Sinner x Rune",
    selection: "Sinner vence 1º set",
    odds: 1.68,
    stake: 75,
    profit: 51,
    status: "green",
  },
  {
    id: "op-004",
    date: "2026-04-24",
    strategyId: "nba-totals",
    market: "Over/Under",
    event: "Lakers x Nuggets",
    selection: "Under 223.5 pontos",
    odds: 1.9,
    stake: 95,
    profit: 85.5,
    status: "green",
  },
  {
    id: "op-005",
    date: "2026-04-25",
    strategyId: "value-live",
    market: "Futebol",
    event: "Benfica x Porto",
    selection: "Ambas marcam",
    odds: 1.76,
    stake: 120,
    profit: -120,
    status: "red",
  },
  {
    id: "op-006",
    date: "2026-04-26",
    strategyId: "corners-pro",
    market: "Escanteios",
    event: "Flamengo x Palmeiras",
    selection: "Over 10.5 cantos",
    odds: 2.05,
    stake: 80,
    profit: 84,
    status: "green",
  },
  {
    id: "op-007",
    date: "2026-04-27",
    strategyId: "tennis-hold",
    market: "Tênis",
    event: "Swiatek x Gauff",
    selection: "Swiatek ML",
    odds: 1.54,
    stake: 70,
    profit: 37.8,
    status: "green",
  },
  {
    id: "op-008",
    date: "2026-04-28",
    strategyId: "nba-totals",
    market: "Over/Under",
    event: "Celtics x Knicks",
    selection: "Over 216.5 pontos",
    odds: 1.87,
    stake: 100,
    profit: -100,
    status: "red",
  },
  {
    id: "op-009",
    date: "2026-04-29",
    strategyId: "value-live",
    market: "Handicap",
    event: "PSG x Marseille",
    selection: "PSG -0.75",
    odds: 1.92,
    stake: 115,
    profit: 105.8,
    status: "green",
  },
  {
    id: "op-010",
    date: "2026-04-30",
    strategyId: "corners-pro",
    market: "Escanteios",
    event: "Liverpool x City",
    selection: "Over 8.5 cantos",
    odds: 1.72,
    stake: 90,
    profit: 64.8,
    status: "green",
  },
  {
    id: "op-011",
    date: "2026-05-01",
    strategyId: "tennis-hold",
    market: "Tênis",
    event: "Alcaraz x Medvedev",
    selection: "Over 22.5 games",
    odds: 1.83,
    stake: 65,
    profit: 0,
    status: "void",
  },
  {
    id: "op-012",
    date: "2026-05-02",
    strategyId: "nba-totals",
    market: "Basquete",
    event: "Warriors x Suns",
    selection: "Warriors +4.5",
    odds: 1.91,
    stake: 90,
    profit: 81.9,
    status: "green",
  },
  {
    id: "op-013",
    date: "2026-05-03",
    strategyId: "value-live",
    market: "Futebol",
    event: "Real Madrid x Atlético",
    selection: "Real Madrid ML",
    odds: 1.66,
    stake: 125,
    profit: 82.5,
    status: "green",
  },
  {
    id: "op-014",
    date: "2026-05-04",
    strategyId: "corners-pro",
    market: "Escanteios",
    event: "Santos x São Paulo",
    selection: "Over 9 cantos asiático",
    odds: 1.81,
    stake: 85,
    profit: -85,
    status: "red",
  },
  {
    id: "op-015",
    date: "2026-05-05",
    strategyId: "value-live",
    market: "Futebol",
    event: "Inter x Milan",
    selection: "Inter empate anula",
    odds: 1.74,
    stake: 100,
    profit: 0,
    status: "open",
  },
];

export const riskPlan: RiskPlan = {
  profile: "moderado",
  initialBankroll,
  currentBankroll: 0,
  maxDailyExposure: 350,
  maxStakePercentage: 2,
  stopLossPercentage: 8,
  takeProfitPercentage: 15,
};

export const bankrollRules: BankrollRule[] = [
  {
    id: "rule-001",
    title: "Stake máxima por entrada",
    description: "Não ultrapassar 2% da banca atual em uma única operação validada.",
    severity: "critical",
  },
  {
    id: "rule-002",
    title: "Stop loss semanal",
    description: "Pausar novas entradas se a perda acumulada da semana atingir 8% da banca.",
    severity: "warning",
  },
  {
    id: "rule-003",
    title: "Revisão de estratégia",
    description: "Estratégias com ROI negativo após 30 entradas entram em quarentena operacional.",
    severity: "info",
  },
  {
    id: "rule-004",
    title: "Reserva de liquidez",
    description: "Manter no mínimo 20% da banca fora de exposição em mercados simultâneos.",
    severity: "warning",
  },
];
